# Generated by Django 3.0.8 on 2020-07-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=500)),
                ('detailed_info', models.CharField(max_length=500)),
                ('our_job', models.CharField(max_length=50)),
                ('job_info', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='showcase')),
                ('box_title', models.CharField(max_length=50)),
                ('box_description', models.CharField(max_length=100)),
                ('box_image', models.ImageField(upload_to='box')),
                ('nav', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quote_title', models.CharField(max_length=50)),
            ],
        ),
    ]
