# Generated by Django 3.0.8 on 2020-07-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='nav',
            new_name='footer',
        ),
    ]
