# Generated by Django 3.0.8 on 2020-07-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmeapp', '0003_auto_20200726_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='footer',
            field=models.CharField(default='Acme Web Design, Copyright &copy; 2017', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='footer',
            field=models.CharField(default='Acme Web Design, Copyright &copy; 2017', max_length=50),
        ),
    ]
